// Generates the repository README catalog and each plugin's README from the
// marketplace manifest, the plugin manifests, and the component frontmatter.
//
//   npm run build            write the generated files
//   npm run check            report drift and exit non-zero
//
// The script reads marketplace.json, walks each plugin, and rewrites the
// generated content. The repository README keeps its hand-written text. Only the
// content between the marker comments is replaced. Each plugin README is written
// in full. It runs on Node's built-in TypeScript support, so it needs no
// install: see package.json for the exact command.
//
// This generator and the validate-readme workflow are adapted from
// github/awesome-copilot (MIT, Copyright GitHub, Inc.). See ATTRIBUTIONS.md.

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const GENERATED_NOTE =
  "<!-- Generated by eng/generate-readmes.ts. Do not edit this file by hand. -->";

interface Component {
  name: string;
  description: string;
  version: string;
  relPath: string;
}

interface Components {
  skills: Component[];
  commands: Component[];
  agents: Component[];
}

interface Manifest {
  name?: string;
  displayName?: string;
  description?: string;
  version?: string;
  license?: string;
  [key: string]: unknown;
}

interface PluginEntry extends Manifest {
  source?: string;
}

interface Marketplace {
  name: string;
  metadata?: { pluginRoot?: string; repository?: string; [key: string]: unknown };
  plugins?: PluginEntry[];
}

interface Plugin {
  manifest: Manifest;
  components: Components;
  relDir: string;
  marketplaceName: string;
  addTarget: string | null;
  repoUrl: string | null;
}

interface Output {
  file: string;
  content: string;
}

type Frontmatter = Record<string, string | Record<string, string>>;

function read(file: string): string {
  return fs.readFileSync(file, "utf8");
}

function exists(file: string): boolean {
  return fs.existsSync(file);
}

// Parse a small YAML frontmatter block. It handles single-line scalar values
// and one level of nested mapping, which is enough for the skill metadata block
// (for example metadata.version). Values may be wrapped in straight quotes.
function parseFrontmatter(content: string): Frontmatter {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const stripQuotes = (v: string): string =>
    (v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))
      ? v.slice(1, -1)
      : v;
  const out: Frontmatter = {};
  let parent: string | null = null;
  for (const line of match[1].split(/\r?\n/)) {
    if (!line.trim()) continue;
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const indented = /^\s/.test(line);
    const key = line.slice(0, idx).trim();
    if (!key) continue;
    const value = stripQuotes(line.slice(idx + 1).trim());
    if (indented && parent) {
      if (typeof out[parent] !== "object") out[parent] = {};
      (out[parent] as Record<string, string>)[key] = value;
    } else if (value === "") {
      out[key] = "";
      parent = key;
    } else {
      out[key] = value;
      parent = null;
    }
  }
  return out;
}

// Make a string safe to place inside a Markdown table cell.
function cell(text: unknown): string {
  return String(text ?? "").replace(/\r?\n/g, " ").replace(/\|/g, "\\|").trim();
}

// Turn a GitHub repository URL into an "owner/repo" slug.
function repoSlug(repoUrl: string | null): string | null {
  if (!repoUrl) return null;
  const m = repoUrl.match(/github\.com[:/]([^/]+\/[^/]+?)(?:\.git)?\/?$/);
  return m ? m[1] : null;
}

// Strip a git+ prefix and a .git suffix so the URL works as a web link.
function webUrl(url: string | null | undefined): string | null {
  return url ? url.replace(/^git\+/, "").replace(/\.git$/, "") : null;
}

// Read the repository URL from package.json. It is kept there, rather than in
// the marketplace manifest, so the marketplace manifest has no fields that the
// plugin validator does not recognize.
function packageRepository(): string | null {
  const pkgPath = path.join(ROOT, "package.json");
  if (!exists(pkgPath)) return null;
  const pkg = JSON.parse(read(pkgPath)) as { repository?: string | { url?: string }; homepage?: string };
  if (pkg.repository) {
    return typeof pkg.repository === "string" ? pkg.repository : pkg.repository.url ?? null;
  }
  return pkg.homepage ?? null;
}

function table(headers: string[], rows: string[][]): string {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((row) => `| ${row.join(" | ")} |`).join("\n");
  return [head, sep, body].join("\n");
}

// Read the components in a plugin from the default folders.
function readComponents(pluginDir: string): Components {
  const collect = (dir: string, isDirEntry: boolean): Component[] => {
    const items: Component[] = [];
    const base = path.join(pluginDir, dir);
    if (!exists(base)) return items;
    for (const name of fs.readdirSync(base).sort()) {
      let file: string;
      let fallbackName: string;
      if (isDirEntry) {
        file = path.join(base, name, "SKILL.md");
        fallbackName = name;
      } else {
        if (!name.endsWith(".md")) continue;
        file = path.join(base, name);
        fallbackName = name.replace(/\.md$/, "");
      }
      if (!exists(file)) continue;
      const fm = parseFrontmatter(read(file));
      const metadata = fm["metadata"];
      const version =
        (metadata && typeof metadata === "object" ? metadata.version : "") ||
        (typeof fm["version"] === "string" ? (fm["version"] as string) : "") ||
        "";
      items.push({
        name: (fm["name"] as string) || fallbackName,
        description: (fm["description"] as string) || "",
        version,
        relPath: path.relative(ROOT, file),
      });
    }
    return items;
  };

  return {
    skills: collect("skills", true),
    commands: collect("commands", false),
    agents: collect("agents", false),
  };
}

function replaceBetween(content: string, begin: string, end: string, inner: string): string {
  const b = content.indexOf(begin);
  const e = content.indexOf(end);
  if (b === -1 || e === -1) {
    throw new Error(`Could not find markers ${begin} ... ${end} in README.md`);
  }
  return content.slice(0, b + begin.length) + "\n\n" + inner.trim() + "\n\n" + content.slice(e);
}

function pluginReadme(plugin: Plugin): string {
  const { manifest, components, marketplaceName, addTarget, repoUrl } = plugin;
  const { skills, commands, agents } = components;
  const lines: string[] = [];

  lines.push(GENERATED_NOTE, "");
  lines.push(`# ${manifest.displayName || manifest.name}`, "");
  if (manifest.description) lines.push(manifest.description, "");

  lines.push("## Install", "");
  lines.push(
    "This plugin follows the [Open Plugin Specification](https://github.com/vercel-labs/open-plugin-spec), so any host that supports the spec can load it. Copy the plugin folder into your project, or add this repository as a marketplace in your host.",
    ""
  );
  lines.push("For example, in a host that uses slash commands:", "");
  lines.push("```");
  if (addTarget) lines.push(`/plugin marketplace add ${addTarget}`);
  lines.push(`/plugin install ${manifest.name}@${marketplaceName}`);
  lines.push("```", "");

  lines.push("## What's included", "");
  if (!skills.length && !commands.length && !agents.length) {
    lines.push("This plugin does not declare any components yet.", "");
  }
  const pluginVersion = manifest.version || "";
  const section = (heading: string, label: string, items: Component[]): void => {
    if (!items.length) return;
    lines.push(`### ${heading}`, "");
    lines.push(
      table(
        [label, "Version", "Description"],
        items.map((i) => [`\`${cell(i.name)}\``, cell(i.version || pluginVersion), cell(i.description)])
      ),
      ""
    );
  };
  section("Skills", "Skill", skills);
  section("Commands", "Command", commands);
  section("Agents", "Agent", agents);

  lines.push("## License", "");
  const license = manifest.license || "MIT";
  lines.push(
    repoUrl
      ? `${license}. Part of the [${marketplaceName}](${repoUrl}) plugin collection from Skyetrail.`
      : `${license}. Part of the ${marketplaceName} plugin collection from Skyetrail.`
  );
  lines.push("");
  return lines.join("\n");
}

// Open Plugin Specification B.4: a plugin entry "source" is resolved relative
// to metadata.pluginRoot, which itself defaults to the marketplace root.
function resolvePluginDir(source: string, pluginRoot: string): string {
  return path.resolve(ROOT, pluginRoot, source);
}

function main(): void {
  const marketplace = JSON.parse(read(path.join(ROOT, "marketplace.json"))) as Marketplace;
  const marketplaceName = marketplace.name;
  const meta = marketplace.metadata || {};
  const pluginRoot = meta.pluginRoot || ".";
  const repoUrl = webUrl(meta.repository || packageRepository());
  const addTarget = repoSlug(repoUrl);

  const outputs: Output[] = [];
  const plugins: Plugin[] = [];

  for (const entry of marketplace.plugins || []) {
    if (typeof entry.source !== "string") {
      console.warn(`Skipping ${entry.name}: source is not a local path, so no README is generated here.`);
      continue;
    }
    const pluginDir = resolvePluginDir(entry.source, pluginRoot);
    const manifestPath = path.join(pluginDir, ".plugin", "plugin.json");
    const manifest: Manifest = exists(manifestPath) ? (JSON.parse(read(manifestPath)) as Manifest) : {};

    // Vendor mirror. Some hosts, including Claude Code today, read the manifest
    // only from the vendor-prefixed .claude-plugin/ location. The Open Plugin
    // Specification allows the same manifest in more than one location (Section
    // 5.2). The .plugin/plugin.json file stays the source of truth and the
    // generator copies it here. Do not edit the mirror by hand.
    if (exists(manifestPath)) {
      outputs.push({
        file: path.join(pluginDir, ".claude-plugin", "plugin.json"),
        content: read(manifestPath),
      });
    }
    for (const key of ["name", "description", "version", "license", "displayName"] as const) {
      if (manifest[key] == null && entry[key] != null) manifest[key] = entry[key] as string;
    }
    if (!manifest.name) manifest.name = entry.name;

    const plugin: Plugin = {
      manifest,
      components: readComponents(pluginDir),
      relDir: path.relative(ROOT, pluginDir),
      marketplaceName,
      addTarget,
      repoUrl,
    };
    plugins.push(plugin);
    outputs.push({ file: path.join(pluginDir, "README.md"), content: pluginReadme(plugin) });
  }

  // Vendor mirror of the marketplace index, for the same reason as the manifest
  // mirror above. marketplace.json at the repository root stays the source of
  // truth and the generator copies it to .claude-plugin/marketplace.json.
  outputs.push({
    file: path.join(ROOT, ".claude-plugin", "marketplace.json"),
    content: read(path.join(ROOT, "marketplace.json")),
  });

  // Repository README: a plugins table and a flat skills table.
  const pluginsTable = plugins.length
    ? table(
        ["Plugin", "Version", "Description", "Skills", "Commands", "Agents"],
        plugins.map((p) => [
          `[\`${cell(p.manifest.name)}\`](${p.relDir})`,
          cell(p.manifest.version),
          cell(p.manifest.description),
          String(p.components.skills.length),
          String(p.components.commands.length),
          String(p.components.agents.length),
        ])
      )
    : "_No plugins yet._";

  const skillRows: string[][] = [];
  for (const p of plugins) {
    for (const s of p.components.skills) {
      skillRows.push([
        `[\`${cell(s.name)}\`](${s.relPath})`,
        `[\`${cell(p.manifest.name)}\`](${p.relDir})`,
        cell(s.version || p.manifest.version),
        cell(s.description),
      ]);
    }
  }
  const skillsTable = skillRows.length
    ? table(["Skill", "Plugin", "Version", "Description"], skillRows)
    : "_No skills yet._";

  const readmePath = path.join(ROOT, "README.md");
  let readme = read(readmePath);
  readme = replaceBetween(readme, "<!-- BEGIN: plugins -->", "<!-- END: plugins -->", pluginsTable);
  readme = replaceBetween(readme, "<!-- BEGIN: skills -->", "<!-- END: skills -->", skillsTable);
  outputs.push({ file: readmePath, content: readme });

  let changed = 0;
  for (const out of outputs) {
    const current = exists(out.file) ? read(out.file) : null;
    if (current === out.content) continue;
    changed++;
    const rel = path.relative(ROOT, out.file);
    if (CHECK) {
      console.error(`Out of date: ${rel}`);
    } else {
      fs.mkdirSync(path.dirname(out.file), { recursive: true });
      fs.writeFileSync(out.file, out.content);
      console.log(`Wrote ${rel}`);
    }
  }

  if (CHECK && changed > 0) {
    console.error(`\n${changed} file(s) out of date. Run: npm run build`);
    process.exit(1);
  }
  console.log(
    changed === 0
      ? "All generated files are up to date."
      : `${CHECK ? "Would update" : "Updated"} ${changed} file(s).`
  );
}

main();
