// Generates the repository README catalog and each plugin's README from the
// marketplace manifest, the plugin manifests, and the component frontmatter.
//
//   npm run build            write the generated files
//   npm run check            report drift and exit non-zero
//
// The script reads marketplace.json at the repository root, walks each plugin,
// and rewrites the generated content. The repository README keeps its
// hand-written text. Only the content between the marker comments is replaced.
// Each plugin README is written in full. It runs on Node with no install and no
// dependencies.
//
// This generator and the validate-readme workflow are adapted from
// github/awesome-copilot (MIT, Copyright GitHub, Inc.). See ATTRIBUTIONS.md.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");

const GENERATED_NOTE =
  "<!-- Generated by eng/generate-readmes.mjs. Do not edit this file by hand. -->";

function read(file) {
  return fs.readFileSync(file, "utf8");
}

function exists(file) {
  return fs.existsSync(file);
}

// Parse a small YAML frontmatter block. It handles single-line scalar values
// and one level of nested mapping, which is enough for the skill metadata block
// (for example metadata.version). Values may be wrapped in straight quotes.
function parseFrontmatter(content) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};
  const stripQuotes = (v) =>
    (v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))
      ? v.slice(1, -1)
      : v;
  const out = {};
  let parent = null;
  for (const line of match[1].split(/\r?\n/)) {
    if (!line.trim()) continue;
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const indented = /^\s/.test(line);
    const key = line.slice(0, idx).trim();
    if (!key) continue;
    const value = stripQuotes(line.slice(idx + 1).trim());
    if (indented && parent) {
      if (typeof out[parent] !== "object") out[parent] = {};
      out[parent][key] = value;
    } else if (value === "") {
      out[key] = "";
      parent = key;
    } else {
      out[key] = value;
      parent = null;
    }
  }
  return out;
}

// Make a string safe to place inside a Markdown table cell.
function cell(text) {
  return String(text ?? "").replace(/\r?\n/g, " ").replace(/\|/g, "\\|").trim();
}

// Turn a GitHub repository URL into an "owner/repo" slug.
function repoSlug(repoUrl) {
  if (!repoUrl) return null;
  const m = repoUrl.match(/github\.com[:/]([^/]+\/[^/]+?)(?:\.git)?\/?$/);
  return m ? m[1] : null;
}

// Strip a git+ prefix and a .git suffix so the URL works as a web link.
function webUrl(url) {
  return url ? url.replace(/^git\+/, "").replace(/\.git$/, "") : null;
}

// Read the repository URL from package.json. It is kept there, rather than in
// the marketplace manifest, so the marketplace manifest has no fields that the
// plugin validator does not recognize.
function packageRepository() {
  const pkgPath = path.join(ROOT, "package.json");
  if (!exists(pkgPath)) return null;
  const pkg = JSON.parse(read(pkgPath));
  if (pkg.repository) {
    return typeof pkg.repository === "string" ? pkg.repository : pkg.repository.url ?? null;
  }
  return pkg.homepage ?? null;
}

// Mechanical lint. The generator already opens every manifest and component
// file, so the limits are enforced here and a violation stops the build before
// any generated file is written. Judgment rules stay in the skills' rule files;
// this checks only what a script can decide.
const MAX_NAME = 64; // Agent Skills frontmatter name limit
const MAX_DESCRIPTION = 1024; // Agent Skills frontmatter description limit
const MAX_BODY_LINES = 500; // recommended SKILL.md body length
const NAME_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const lintProblems = [];

function lintProblem(file, msg) {
  lintProblems.push(`${path.relative(ROOT, file)}: ${msg}`);
}

// Checks one component markdown file. dirName is the skill directory name for
// directory-based skills, or null for flat command and agent files.
function lintComponent(file, content, dirName) {
  const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) {
    lintProblem(file, "no frontmatter block");
    return;
  }

  // YAML hazards the tolerant parser here would hide: an unquoted value with
  // ": " fails to parse in real YAML, and an unquoted "#" silently truncates
  // the value as a comment.
  for (const line of match[1].split(/\r?\n/)) {
    if (/^\s/.test(line)) continue;
    const m = line.match(/^([A-Za-z0-9_-]+):\s+(.*)$/);
    if (!m) continue;
    const [, key, value] = m;
    if (value.startsWith('"') || value.startsWith("'")) continue;
    if (value.includes(": ")) lintProblem(file, `unquoted ": " in ${key} breaks YAML; quote the value`);
    if (value.includes(" #")) lintProblem(file, `unquoted "#" in ${key} starts a YAML comment; quote the value`);
  }

  const fm = parseFrontmatter(content);
  const name = typeof fm.name === "string" ? fm.name : "";
  const description = typeof fm.description === "string" ? fm.description : "";

  if (!name) lintProblem(file, "frontmatter has no name");
  else {
    if (name.length > MAX_NAME) lintProblem(file, `name is ${name.length} characters; the limit is ${MAX_NAME}`);
    if (!NAME_RE.test(name)) lintProblem(file, "name must be lowercase letters, numbers, and single hyphens");
    if (dirName && name !== dirName) lintProblem(file, `name "${name}" does not match directory "${dirName}"`);
  }

  if (!description) lintProblem(file, "frontmatter has no description");
  else if (description.length > MAX_DESCRIPTION) {
    lintProblem(file, `description is ${description.length} characters; the limit is ${MAX_DESCRIPTION}`);
  }

  const body = content.slice(match[0].length);
  const bodyLines = body.trim() ? body.replace(/^\n+/, "").replace(/\n+$/, "").split("\n").length : 0;
  if (bodyLines > MAX_BODY_LINES) {
    lintProblem(file, `body is ${bodyLines} lines; the limit is ${MAX_BODY_LINES}`);
  }

  lintReferences(file, content);
}

// Reference checks shared by component files and plugin reference files.
function lintReferences(file, content) {
  for (const link of content.matchAll(/\[([^\]]*)\]\(([^)]+)\)/g)) {
    const target = link[2].split("#")[0].trim();
    if (!target || /^(https?:\/\/|mailto:)/.test(target)) continue;
    if (!exists(path.normalize(path.join(path.dirname(file), target)))) {
      lintProblem(file, `reference does not resolve: ${link[2]}`);
    }
    // When the link text reads as a filename, it must be the filename it
    // links to, so the reader is never sent somewhere the text does not say.
    const text = link[1].replace(/`/g, "").trim();
    if (/\.md$/i.test(text) && text !== path.basename(target)) {
      lintProblem(file, `link text "${text}" does not match the target filename "${path.basename(target)}"`);
    }
  }

  // Relative paths in backticks are how these skills name their references.
  for (const tick of content.matchAll(/`(\.{1,2}\/[^`\n]+\.md)`/g)) {
    if (!exists(path.normalize(path.join(path.dirname(file), tick[1])))) {
      lintProblem(file, `reference does not resolve: ${tick[1]}`);
    }
  }
}

function table(headers, rows) {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((row) => `| ${row.join(" | ")} |`).join("\n");
  return [head, sep, body].join("\n");
}

// Read the components in a plugin from the default folders.
function readComponents(pluginDir) {
  const collect = (dir, isDirEntry) => {
    const items = [];
    const base = path.join(pluginDir, dir);
    if (!exists(base)) return items;
    for (const name of fs.readdirSync(base).sort()) {
      let file;
      let fallbackName;
      if (isDirEntry) {
        file = path.join(base, name, "SKILL.md");
        fallbackName = name;
      } else {
        if (!name.endsWith(".md")) continue;
        file = path.join(base, name);
        fallbackName = name.replace(/\.md$/, "");
      }
      if (!exists(file)) continue;
      const content = read(file);
      lintComponent(file, content, isDirEntry ? name : null);
      const fm = parseFrontmatter(content);
      const metadata = fm.metadata;
      const version =
        (metadata && typeof metadata === "object" ? metadata.version : "") ||
        (typeof fm.version === "string" ? fm.version : "") ||
        "";
      items.push({
        name: fm.name || fallbackName,
        description: fm.description || "",
        version,
        relPath: path.relative(ROOT, file),
      });
    }
    return items;
  };

  return {
    skills: collect("skills", true),
    commands: collect("commands", false),
    agents: collect("agents", false),
  };
}

function replaceBetween(content, begin, end, inner) {
  const b = content.indexOf(begin);
  const e = content.indexOf(end);
  if (b === -1 || e === -1) {
    throw new Error(`Could not find markers ${begin} ... ${end} in README.md`);
  }
  return content.slice(0, b + begin.length) + "\n\n" + inner.trim() + "\n\n" + content.slice(e);
}

function pluginReadme(plugin) {
  const { manifest, components, marketplaceName, addTarget, repoUrl } = plugin;
  const { skills, commands, agents } = components;
  const lines = [];

  lines.push(GENERATED_NOTE, "");
  lines.push(`# ${manifest.displayName || manifest.name}`, "");
  if (manifest.description) lines.push(manifest.description, "");

  lines.push("## Install", "");
  lines.push(
    "This plugin follows the [Agent Plugins specification](https://agent-plugins.org), so any client that supports the spec can load it. Copy the plugin folder into your project, or add this repository as a marketplace in your host.",
    ""
  );
  lines.push("For example, in a host that uses slash commands:", "");
  lines.push("```");
  if (addTarget) lines.push(`/plugin marketplace add ${addTarget}`);
  lines.push(`/plugin install ${manifest.name}@${marketplaceName}`);
  lines.push("```", "");

  lines.push("## What's included", "");
  if (!skills.length && !commands.length && !agents.length) {
    lines.push("This plugin does not declare any components yet.", "");
  }
  const pluginVersion = manifest.version || "";
  const section = (heading, label, items) => {
    if (!items.length) return;
    lines.push(`### ${heading}`, "");
    lines.push(
      table(
        [label, "Version", "Description"],
        items.map((i) => [`\`${cell(i.name)}\``, cell(i.version || pluginVersion), cell(i.description)])
      ),
      ""
    );
  };
  section("Skills", "Skill", skills);
  section("Commands", "Command", commands);
  section("Agents", "Agent", agents);

  if (plugin.summary) {
    lines.push(plugin.summary.trim(), "");
  }

  if (plugin.hasTests) {
    lines.push("## Evidence", "");
    lines.push(
      "The skills in this plugin were tested before adoption: baseline comparisons with and without each skill loaded, audit rounds against the shared rules, and a description A/B. The full narrative is in [TEST_REPORT.md](tests/TEST_REPORT.md), and the per-skill baseline records are in [tests/baselines/](tests/baselines/).",
      ""
    );
  }

  lines.push("## License", "");
  const license = manifest.license || "MIT";
  lines.push(
    repoUrl
      ? `${license}. Part of the [${marketplaceName}](${repoUrl}) plugin collection from Skyetrail.`
      : `${license}. Part of the ${marketplaceName} plugin collection from Skyetrail.`
  );
  lines.push("");
  return lines.join("\n");
}

// Open Plugin Specification B.4: a plugin entry "source" is resolved relative
// to metadata.pluginRoot, which itself defaults to the marketplace root.
function resolvePluginDir(source, pluginRoot) {
  return path.resolve(ROOT, pluginRoot, source);
}

// The catalog's source of truth is marketplace.json at the repository root,
// the neutral location. The Agent Plugins specification leaves distribution
// out of scope, so the root location is this repository's convention. Claude
// Code's installer reads the catalog only from .claude-plugin/marketplace.json
// (verified against CLI 2.1.179), so the generator writes that copy as a shim.
const CATALOG = path.join(ROOT, "marketplace.json");

function main() {
  const marketplace = JSON.parse(read(CATALOG));
  const marketplaceName = marketplace.name;
  const meta = marketplace.metadata || {};
  const pluginRoot = meta.pluginRoot || ".";
  const repoUrl = webUrl(meta.repository || packageRepository());
  const addTarget = repoSlug(repoUrl);

  const outputs = [];
  const plugins = [];

  for (const entry of marketplace.plugins || []) {
    if (typeof entry.source !== "string") {
      console.warn(`Skipping ${entry.name}: source is not a local path, so no README is generated here.`);
      continue;
    }
    const pluginDir = resolvePluginDir(entry.source, pluginRoot);
    if (!exists(pluginDir)) {
      lintProblem(CATALOG, `plugin source does not exist: ${entry.source}`);
      continue;
    }
    if (entry.name && !NAME_RE.test(entry.name)) {
      lintProblem(CATALOG, `plugin name "${entry.name}" must be lowercase letters, numbers, and single hyphens`);
    }
    // Agent Plugins (agent-plugins.org): one manifest, plugin.json, at the
    // plugin root. Claude Code ignores it and takes metadata from the
    // marketplace entry, so no per-plugin mirror is needed.
    const manifestPath = path.join(pluginDir, "plugin.json");
    const manifest = exists(manifestPath) ? JSON.parse(read(manifestPath)) : {};
    if (!exists(manifestPath)) {
      lintProblem(pluginDir, "no plugin.json manifest at the plugin root; Agent Plugins requires one");
    } else if (manifest["$schema"] !== "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json") {
      lintProblem(manifestPath, 'plugin.json must declare "$schema": "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"');
    }
    if (manifest.name && !NAME_RE.test(manifest.name)) {
      lintProblem(manifestPath, `plugin name "${manifest.name}" must be lowercase letters, numbers, and single hyphens`);
    }
    for (const key of ["name", "description", "version", "license", "displayName"]) {
      if (manifest[key] == null && entry[key] != null) manifest[key] = entry[key];
    }
    if (!manifest.name) manifest.name = entry.name;

    // Lint the plugin's shared reference files too: they load with the skills
    // that name them. tests/ and the working notes are deliberately excluded,
    // since they are historical records that may cite paths from earlier
    // rounds.
    const sharedDir = path.join(pluginDir, "shared");
    if (exists(sharedDir)) {
      for (const name of fs.readdirSync(sharedDir).sort()) {
        if (name.endsWith(".md")) {
          const file = path.join(sharedDir, name);
          lintReferences(file, read(file));
        }
      }
    }

    // An optional hand-written SUMMARY.md at the plugin root is included
    // verbatim in the generated README and linted like any reference surface.
    const summaryPath = path.join(pluginDir, "SUMMARY.md");
    let summary = null;
    if (exists(summaryPath)) {
      summary = read(summaryPath);
      lintReferences(summaryPath, summary);
    }

    const plugin = {
      manifest,
      components: readComponents(pluginDir),
      relDir: path.relative(ROOT, pluginDir),
      marketplaceName,
      addTarget,
      repoUrl,
      hasTests: exists(path.join(pluginDir, "tests", "TEST_REPORT.md")),
      summary,
    };
    plugins.push(plugin);
    outputs.push({ file: path.join(pluginDir, "README.md"), content: pluginReadme(plugin) });
  }

  // The installer shim: a generated copy of the root catalog at the one path
  // Claude Code reads. Do not edit the copy by hand.
  outputs.push({
    file: path.join(ROOT, ".claude-plugin", "marketplace.json"),
    content: read(CATALOG),
  });

  // Repository README: a plugins table and a flat skills table.
  const pluginsTable = plugins.length
    ? table(
        ["Plugin", "Version", "Description", "Skills", "Commands", "Agents"],
        plugins.map((p) => [
          `[\`${cell(p.manifest.name)}\`](${p.relDir})`,
          cell(p.manifest.version),
          cell(p.manifest.description),
          String(p.components.skills.length),
          String(p.components.commands.length),
          String(p.components.agents.length),
        ])
      )
    : "_No plugins yet._";

  const skillRows = [];
  for (const p of plugins) {
    for (const s of p.components.skills) {
      skillRows.push([
        `[\`${cell(s.name)}\`](${s.relPath})`,
        `[\`${cell(p.manifest.name)}\`](${p.relDir})`,
        cell(s.version || p.manifest.version),
        cell(s.description),
      ]);
    }
  }
  const skillsTable = skillRows.length
    ? table(["Skill", "Plugin", "Version", "Description"], skillRows)
    : "_No skills yet._";

  const readmePath = path.join(ROOT, "README.md");
  let readme = read(readmePath);
  readme = replaceBetween(readme, "<!-- BEGIN: plugins -->", "<!-- END: plugins -->", pluginsTable);
  readme = replaceBetween(readme, "<!-- BEGIN: skills -->", "<!-- END: skills -->", skillsTable);
  outputs.push({ file: readmePath, content: readme });

  if (lintProblems.length) {
    for (const p of lintProblems) console.error(`lint: ${p}`);
    console.error(`\n${lintProblems.length} lint problem(s). Nothing was written.`);
    process.exit(1);
  }

  let changed = 0;
  for (const out of outputs) {
    const current = exists(out.file) ? read(out.file) : null;
    if (current === out.content) continue;
    changed++;
    const rel = path.relative(ROOT, out.file);
    if (CHECK) {
      console.error(`Out of date: ${rel}`);
    } else {
      fs.mkdirSync(path.dirname(out.file), { recursive: true });
      fs.writeFileSync(out.file, out.content);
      console.log(`Wrote ${rel}`);
    }
  }

  if (CHECK && changed > 0) {
    console.error(`\n${changed} file(s) out of date. Run: npm run build`);
    process.exit(1);
  }
  console.log(
    changed === 0
      ? "All generated files are up to date."
      : `${CHECK ? "Would update" : "Updated"} ${changed} file(s).`
  );
}

main();
