// Generates the repository README catalog and each plugin's README from the
// marketplace manifest, the plugin manifests, and the component frontmatter.
//
//   npm run build            write the generated files
//   npm run check            report drift and exit non-zero
//   npm run lint -- --explain   print which checks each kind of file gets
//
// The script reads marketplace.json at the repository root, walks each plugin,
// and rewrites the generated content. The repository README keeps its
// hand-written text. Only the content between the marker comments is replaced.
// Each plugin README is written in full. It runs on Node with no install and no
// dependencies.
//
// This generator and the validate-readme workflow are adapted from
// github/awesome-copilot (MIT, Copyright GitHub, Inc.). See ATTRIBUTIONS.md.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  CONTENTS_REQUIRED_LINES,
  MAX_BODY_LINES,
  MAX_DESCRIPTION,
  NAME_RE,
  check,
  fileContext,
  parseFrontmatter,
  referencedMarkdown,
  runChecks,
} from "./skill-checks.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CHECK = process.argv.includes("--check");
const EXPLAIN = process.argv.includes("--explain");

const GENERATED_NOTE =
  "<!-- Generated by eng/generate-readmes.mjs. Do not edit this file by hand. -->";

function read(file) {
  return fs.readFileSync(file, "utf8");
}

function exists(file) {
  return fs.existsSync(file);
}

// Make a string safe to place inside a Markdown table cell.
function cell(text) {
  return String(text ?? "").replace(/\r?\n/g, " ").replace(/\|/g, "\\|").trim();
}

// Turn a GitHub repository URL into an "owner/repo" slug.
function repoSlug(repoUrl) {
  if (!repoUrl) return null;
  const m = repoUrl.match(/github\.com[:/]([^/]+\/[^/]+?)(?:\.git)?\/?$/);
  return m ? m[1] : null;
}

// Strip a git+ prefix and a .git suffix so the URL works as a web link.
function webUrl(url) {
  return url ? url.replace(/^git\+/, "").replace(/\.git$/, "") : null;
}

// Read the repository URL from package.json. It is kept there, rather than in
// the marketplace manifest, so the marketplace manifest has no fields that the
// plugin validator does not recognize.
function packageRepository() {
  const pkgPath = path.join(ROOT, "package.json");
  if (!exists(pkgPath)) return null;
  const pkg = JSON.parse(read(pkgPath));
  if (pkg.repository) {
    return typeof pkg.repository === "string" ? pkg.repository : pkg.repository.url ?? null;
  }
  return pkg.homepage ?? null;
}

// Mechanical lint. The generator already opens every manifest and component
// file, so the limits are enforced here and a violation stops the build before
// any generated file is written. Judgment rules stay in the skills' rule files;
// this checks only what a script can decide.
//
// The checks themselves live in eng/skill-checks.mjs, which holds every
// mechanical check this repository makes. This build runs the subset that
// guards the repository. `npm run audit` runs the whole set against one skill.
// The lists below name that subset, in the order the findings print.
const COMPONENT_CHECKS = [
  "lint-frontmatter-present",
  "lint-yaml-colon-space",
  "lint-yaml-hash",
  "lint-name-present",
  "lint-name-length",
  "lint-name-format",
  "lint-name-matches-directory",
  "lint-description-present",
  "lint-description-length",
  "lint-body-length",
  "lint-reference-resolves",
  "lint-link-text-matches-filename",
  ];
const REFERENCED_CHECKS = ["lint-contents-list", ];
const SURFACE_CHECKS = [
  "lint-reference-resolves",
  "lint-link-text-matches-filename",
  "lint-contents-list",
  ];
const lintProblems = [];
const lintAdvisories = [];

// What this lint covers, as data. The run below reads it to decide what to
// open, and `--explain` prints it, so what we check and what we say we check
// cannot drift apart. A prose copy of this in a document went wrong four times
// in two days before it was moved here.
const COMPONENT_KINDS = [
  { key: "skills", dir: "skills", perDirectory: true },
  { key: "commands", dir: "commands", perDirectory: false },
  { key: "agents", dir: "agents", perDirectory: false },
];

const REFERENCE_SURFACES = [
  {
    describe: "a top-level .md under a plugin's shared/",
    find: (pluginDir) => {
      const dir = path.join(pluginDir, "shared");
      if (!exists(dir)) return [];
      return fs
        .readdirSync(dir)
        .sort()
        .filter((name) => name.endsWith(".md"))
        .map((name) => path.join(dir, name));
    },
  },
  {
    describe: "a plugin's SUMMARY.md",
    find: (pluginDir) => {
      const file = path.join(pluginDir, "SUMMARY.md");
      return exists(file) ? [file] : [];
    },
  },
];

const EXCLUDED = "anything under a plugin's tests/, which are records that may cite paths from earlier rounds";

// Prints the check lists above, one entry per check, so what this command says
// it checks and what it runs cannot drift apart. Do not describe a check here
// in prose. Add it to a list and let it print itself.
function explainCoverage() {
  const lines = [
    "What `npm run lint` opens, and which checks each kind of file gets.",
    "",
    "This command guards the repository, so it runs a subset of the checks.",
    "`npm run audit -- <path>` runs every mechanical check against one skill,",
    "including the ones on bundled scripts and evaluation records, and",
    "`npm run audit -- --explain` prints that whole set.",
    "",
    `Limits held here: description ${MAX_DESCRIPTION} characters, body ${MAX_BODY_LINES} lines,`,
    `contents list over ${CONTENTS_REQUIRED_LINES} lines.`,
    "",
  ];
  const listChecks = (ids) => {
    const seen = [...new Set(ids)].map((id) => check(id));
    const width = Math.max(...seen.map((c) => c.id.length));
    for (const c of seen) {
      const mark = c.severity === "advisory" ? "advisory" : "fail    ";
      lines.push(`    ${c.id.padEnd(width)}  ${mark}  ${c.requires}`);
    }
  };

  lines.push("A component carries frontmatter. It gets:");
  listChecks(COMPONENT_CHECKS);
  lines.push("", "  A component is:");
  for (const kind of COMPONENT_KINDS) {
    const where = kind.perDirectory ? `${kind.dir}/*/SKILL.md` : `${kind.dir}/*.md`;
    lines.push(`  - ${where}`);
  }

  lines.push("", "Every .md a component links to gets:");
  listChecks(REFERENCED_CHECKS);

  lines.push("", "A reference surface carries no frontmatter, so the frontmatter and");
  lines.push("description checks do not reach it. It gets:");
  listChecks(SURFACE_CHECKS);
  lines.push("", "  A reference surface is:");
  for (const surface of REFERENCE_SURFACES) lines.push(`  - ${surface.describe}`);

  lines.push("", "An advisory finding prints once and never stops the run. A fail stops the");
  lines.push("build before anything is written.");
  lines.push("", `Not opened at all: ${EXCLUDED}.`);
  lines.push("");
  lines.push("A target that is none of the above was not checked by this command. Say which");
  lines.push("checks did not reach it rather than reporting a pass or a total gap.");
  return lines.join("\n");
}

function lintProblem(file, msg) {
  lintProblems.push(`${path.relative(ROOT, file)}: ${msg}`);
}

// Record what one check found. A fail stops the build; an advisory prints and
// does not, because the rule files give Advisory that meaning.
function record(file, results) {
  for (const result of results) {
    for (const msg of result.messages) {
      const line = `${path.relative(ROOT, file)}: ${msg}`;
      if (result.severity === "advisory") lintAdvisories.push(line);
      else lintProblems.push(line);
    }
  }
}

// Checks one component markdown file. dirName is the skill directory name for
// directory-based skills, or null for flat command and agent files.
function lintComponent(file, content, dirName) {
  const ctx = fileContext(file, content, { dirName });
  if (ctx.frontmatter === null) {
    record(file, runChecks(["lint-frontmatter-present"], ctx));
    return;
  }
  record(file, runChecks(COMPONENT_CHECKS, ctx));
  for (const ref of referencedMarkdown(file, content)) {
    record(ref, runChecks(REFERENCED_CHECKS, fileContext(ref, read(ref))));
  }
}

// A reference surface carries no frontmatter, so it gets the file-level checks
// only: references, contents list and sentence caps.
function lintReferenceSurface(file, content) {
  record(file, runChecks(SURFACE_CHECKS, fileContext(file, content)));
}

function table(headers, rows) {
  const head = `| ${headers.join(" | ")} |`;
  const sep = `| ${headers.map(() => "---").join(" | ")} |`;
  const body = rows.map((row) => `| ${row.join(" | ")} |`).join("\n");
  return [head, sep, body].join("\n");
}

// Read the components in a plugin from the default folders.
function readComponents(pluginDir) {
  const collect = (dir, isDirEntry) => {
    const items = [];
    const base = path.join(pluginDir, dir);
    if (!exists(base)) return items;
    for (const name of fs.readdirSync(base).sort()) {
      let file;
      let fallbackName;
      if (isDirEntry) {
        file = path.join(base, name, "SKILL.md");
        fallbackName = name;
      } else {
        if (!name.endsWith(".md")) continue;
        file = path.join(base, name);
        fallbackName = name.replace(/\.md$/, "");
      }
      if (!exists(file)) continue;
      const content = read(file);
      lintComponent(file, content, isDirEntry ? name : null);
      const fm = parseFrontmatter(content);
      const metadata = fm.metadata;
      const version =
        (metadata && typeof metadata === "object" ? metadata.version : "") ||
        (typeof fm.version === "string" ? fm.version : "") ||
        "";
      items.push({
        name: fm.name || fallbackName,
        description: fm.description || "",
        version,
        relPath: path.relative(ROOT, file),
      });
    }
    return items;
  };

  return Object.fromEntries(
    COMPONENT_KINDS.map((kind) => [kind.key, collect(kind.dir, kind.perDirectory)])
  );
}

function replaceBetween(content, begin, end, inner) {
  const b = content.indexOf(begin);
  const e = content.indexOf(end);
  if (b === -1 || e === -1) {
    throw new Error(`Could not find markers ${begin} ... ${end} in README.md`);
  }
  return content.slice(0, b + begin.length) + "\n\n" + inner.trim() + "\n\n" + content.slice(e);
}

function pluginReadme(plugin) {
  const { manifest, components, marketplaceName, addTarget, repoUrl } = plugin;
  const { skills, commands, agents } = components;
  const lines = [];

  lines.push(GENERATED_NOTE, "");
  lines.push(`# ${manifest.displayName || manifest.name}`, "");
  if (manifest.description) lines.push(manifest.description, "");

  lines.push("## Install", "");
  lines.push(
    "This plugin follows the [Agent Plugins specification](https://agent-plugins.org), so any client that supports the spec can load it. Copy the plugin folder into your project, or add this repository as a marketplace in your host.",
    ""
  );
  lines.push("In a host that uses slash commands:", "");
  lines.push("```");
  if (addTarget) lines.push(`/plugin marketplace add ${addTarget}`);
  lines.push(`/plugin install ${manifest.name}@${marketplaceName}`);
  lines.push("```", "");

  lines.push("## What's included", "");
  if (!skills.length && !commands.length && !agents.length) {
    lines.push("This plugin does not declare any components yet.", "");
  }
  const pluginVersion = manifest.version || "";
  const section = (heading, label, items) => {
    if (!items.length) return;
    lines.push(`### ${heading}`, "");
    lines.push(
      table(
        [label, "Version", "Description"],
        items.map((i) => [`\`${cell(i.name)}\``, cell(i.version || pluginVersion), cell(i.description)])
      ),
      ""
    );
  };
  section("Skills", "Skill", skills);
  section("Commands", "Command", commands);
  section("Agents", "Agent", agents);

  if (plugin.summary) {
    lines.push(plugin.summary.trim(), "");
  }

  if (plugin.hasTests && !plugin.summary) {
    lines.push("## Evidence", "");
    lines.push(
      "The skills in this plugin were measured before adoption: isolated runs on the model that executes them, with and without each skill, scored blind against pre-registered rubrics. The results pages are under [tests/outcomes/](tests/outcomes/).",
      ""
    );
  }

  lines.push("## License", "");
  const license = manifest.license || "MIT";
  lines.push(
    repoUrl
      ? `${license}. Part of the [${marketplaceName}](${repoUrl}) plugin collection from Skyetrail.`
      : `${license}. Part of the ${marketplaceName} plugin collection from Skyetrail.`
  );
  lines.push("");
  return lines.join("\n");
}

// Open Plugin Specification B.4: a plugin entry "source" is resolved relative
// to metadata.pluginRoot, which itself defaults to the marketplace root.
function resolvePluginDir(source, pluginRoot) {
  return path.resolve(ROOT, pluginRoot, source);
}

// The catalog's source of truth is marketplace.json at the repository root,
// the neutral location. The Agent Plugins specification leaves distribution
// out of scope, so the root location is this repository's convention. Claude
// Code's installer reads the catalog only from .claude-plugin/marketplace.json
// (verified against CLI 2.1.179), so the generator writes that copy as a shim.
const CATALOG = path.join(ROOT, "marketplace.json");

function main() {
  if (EXPLAIN) {
    console.log(explainCoverage());
    return;
  }

  const marketplace = JSON.parse(read(CATALOG));
  const marketplaceName = marketplace.name;
  const meta = marketplace.metadata || {};
  const pluginRoot = meta.pluginRoot || ".";
  const repoUrl = webUrl(meta.repository || packageRepository());
  const addTarget = repoSlug(repoUrl);

  const outputs = [];
  const plugins = [];

  for (const entry of marketplace.plugins || []) {
    if (typeof entry.source !== "string") {
      console.warn(`Skipping ${entry.name}: source is not a local path, so no README is generated here.`);
      continue;
    }
    const pluginDir = resolvePluginDir(entry.source, pluginRoot);
    if (!exists(pluginDir)) {
      lintProblem(CATALOG, `plugin source does not exist: ${entry.source}`);
      continue;
    }
    if (entry.name && !NAME_RE.test(entry.name)) {
      lintProblem(CATALOG, `plugin name "${entry.name}" must be lowercase letters, numbers, and single hyphens`);
    }
    // Agent Plugins (agent-plugins.org): one manifest, plugin.json, at the
    // plugin root. Claude Code ignores it and takes metadata from the
    // marketplace entry, so no per-plugin mirror is needed.
    const manifestPath = path.join(pluginDir, "plugin.json");
    const manifest = exists(manifestPath) ? JSON.parse(read(manifestPath)) : {};
    if (!exists(manifestPath)) {
      lintProblem(pluginDir, "no plugin.json manifest at the plugin root; Agent Plugins requires one");
    } else if (manifest["$schema"] !== "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json") {
      lintProblem(manifestPath, 'plugin.json must declare "$schema": "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"');
    }
    if (manifest.name && !NAME_RE.test(manifest.name)) {
      lintProblem(manifestPath, `plugin name "${manifest.name}" must be lowercase letters, numbers, and single hyphens`);
    }
    for (const key of ["name", "description", "version", "license", "displayName"]) {
      if (manifest[key] == null && entry[key] != null) manifest[key] = entry[key];
    }
    if (!manifest.name) manifest.name = entry.name;

    // Lint every reference surface: these load alongside the components that
    // name them. REFERENCE_SURFACES is the same list `--explain` prints, so the
    // two cannot disagree.
    for (const surface of REFERENCE_SURFACES) {
      for (const file of surface.find(pluginDir)) {
        lintReferenceSurface(file, read(file));
      }
    }

    // A plugin's SUMMARY.md is also included verbatim in its generated README.
    // It is linted above, as one of the reference surfaces.
    const summaryPath = path.join(pluginDir, "SUMMARY.md");
    const summary = exists(summaryPath) ? read(summaryPath) : null;

    const plugin = {
      manifest,
      components: readComponents(pluginDir),
      relDir: path.relative(ROOT, pluginDir),
      marketplaceName,
      addTarget,
      repoUrl,
      hasTests: exists(path.join(pluginDir, "tests", "outcomes")),
      summary,
    };
    plugins.push(plugin);
    outputs.push({ file: path.join(pluginDir, "README.md"), content: pluginReadme(plugin) });
  }

  // The installer shim: a generated copy of the root catalog at the one path
  // Claude Code reads. Do not edit the copy by hand.
  outputs.push({
    file: path.join(ROOT, ".claude-plugin", "marketplace.json"),
    content: read(CATALOG),
  });

  // Repository README: a plugins table and a flat skills table.
  const pluginsTable = plugins.length
    ? table(
        ["Plugin", "Version", "Description", "Skills", "Commands", "Agents"],
        plugins.map((p) => [
          `[\`${cell(p.manifest.name)}\`](${p.relDir})`,
          cell(p.manifest.version),
          cell(p.manifest.description),
          String(p.components.skills.length),
          String(p.components.commands.length),
          String(p.components.agents.length),
        ])
      )
    : "_No plugins yet._";

  const skillRows = [];
  for (const p of plugins) {
    for (const s of p.components.skills) {
      skillRows.push([
        `[\`${cell(s.name)}\`](${s.relPath})`,
        `[\`${cell(p.manifest.name)}\`](${p.relDir})`,
        cell(s.version || p.manifest.version),
        cell(s.description),
      ]);
    }
  }
  const skillsTable = skillRows.length
    ? table(["Skill", "Plugin", "Version", "Description"], skillRows)
    : "_No skills yet._";

  const readmePath = path.join(ROOT, "README.md");
  let readme = read(readmePath);
  readme = replaceBetween(readme, "<!-- BEGIN: plugins -->", "<!-- END: plugins -->", pluginsTable);
  readme = replaceBetween(readme, "<!-- BEGIN: skills -->", "<!-- END: skills -->", skillsTable);
  outputs.push({ file: readmePath, content: readme });

  // Advisory findings are printed and never stop the run, because the rule
  // files give Advisory that meaning. A lint that failed the build on one would
  // be promoting its severity by implementation.
  // One file reaches this check by more than one route: as a reference surface,
  // and again for each component that links it. The finding is about the file,
  // so report it once.
  for (const w of [...new Set(lintAdvisories)]) console.warn(`lint (advisory): ${w}`);

  if (lintProblems.length) {
    for (const p of lintProblems) console.error(`lint: ${p}`);
    console.error(`\n${lintProblems.length} lint problem(s). Nothing was written.`);
    process.exit(1);
  }

  let changed = 0;
  for (const out of outputs) {
    const current = exists(out.file) ? read(out.file) : null;
    if (current === out.content) continue;
    changed++;
    const rel = path.relative(ROOT, out.file);
    if (CHECK) {
      console.error(`Out of date: ${rel}`);
    } else {
      fs.mkdirSync(path.dirname(out.file), { recursive: true });
      fs.writeFileSync(out.file, out.content);
      console.log(`Wrote ${rel}`);
    }
  }

  if (CHECK && changed > 0) {
    console.error(`\n${changed} file(s) out of date. Run: npm run build`);
    process.exit(1);
  }
  console.log(
    changed === 0
      ? "All generated files are up to date."
      : `${CHECK ? "Would update" : "Updated"} ${changed} file(s).`
  );
}

main();
